# Predict on New Data with OctoPredictor

This notebook demonstrates how to use `OctoPredictor` to predict on new, unseen data after training an Octopus study.

**OctoPredictor vs OctoTestEvaluator:**

|                | OctoPredictor                                              | OctoTestEvaluator                              |
| -------------- | ---------------------------------------------------------- | ---------------------------------------------- |
| **Purpose**    | Predict on new, unseen data                                | Evaluate study results on held-out test folds  |
| **Data**       | You provide data explicitly                                | Uses stored train/test splits from the study   |
| **Prediction** | Ensemble average across all outer-split models             | Each model predicts only on its own test fold  |
| **Deployment** | Can be saved/loaded standalone (no study directory needed) | Requires the full study directory              |
| **Use case**   | Production inference, scoring new patients/samples         | Post-hoc model evaluation, internal validation |

## 1. Train a Study

We split the breast cancer dataset 80/20 — train the study on 80% and hold out 20% as "new" data for prediction.

In [ ]:
import os
import tempfile

import pandas as pd
from sklearn.model_selection import train_test_split

from octopus.example_data import load_breast_cancer_data
from octopus.modules import Octo
from octopus.study import OctoClassification
from octopus.types import ModelName

In [2]:
# Load the breast cancer dataset
df, features, targets = load_breast_cancer_data()

print(f"Full dataset: {df.shape[0]} samples, {len(features)} features")
print(f"Classes: {targets}")
print(f"Target distribution: {df['target'].value_counts().sort_index().to_dict()}")

Full dataset: 569 samples, 30 features
Classes: ['malignant', 'benign']
Target distribution: {0: 212, 1: 357}

In [3]:
# Split 80/20: train the study on train_df, predict on new_df later
train_df, new_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df["target"])
train_df = train_df.reset_index(drop=True)
new_df = new_df.reset_index(drop=True)

print(f"Training set: {train_df.shape[0]} samples")
print(f"New data (held-out): {new_df.shape[0]} samples")

Training set: 455 samples
New data (held-out): 114 samples

In [5]:
# Create and fit a classification study (2 outer folds, 5 trials for speed)
study = OctoClassification(
    study_name="predict_example",
    studies_directory=os.environ.get("STUDIES_PATH", "./studies"),
    target_metric="AUCROC",
    feature_cols=features,
    target_col="target",
    sample_id_col="index",
    stratification_col="target",
    n_outer_splits=2,
    n_cpus=1,
    workflow=[
        Octo(
            description="step1_octo",
            task_id=0,
            depends_on=None,
            models=[ModelName.ExtraTreesClassifier],
            n_trials=5,
            n_inner_splits=3,
        ),
    ],
)

study.fit(data=train_df)
print(f"Study saved to: {study.output_path}")

INFO | CREATING_DATASPLITS | 455 rows, 455 groups (column: datasplit_group), StratifiedGroupKFold, 2 splits, seed 0
INFO | CREATING_DATASPLITS | Outer 0 created: Train/Dev - 228 rows, 228 groups | Test - 227 rows, 227 groups
INFO | CREATING_DATASPLITS | Outer 1 created: Train/Dev - 227 rows, 227 groups | Test - 228 rows, 228 groups
INFO | CREATING_DATASPLITS | Creating a local ray instance with 1 CPUs.

2026-04-10 16:47:25,585	INFO worker.py:2014 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265

INFO | CREATING_DATASPLITS | Preparing execution |
Single outer split: False
Outer splits:      2
Available CPUs:    1
Workers:           1
CPUs/outer split:  1
Ray Nodes:
	Node __internal_head__, 127.0.0.1:  1.0 CPUs
INFO | PROCESSING | Running outer split: 0
INFO | PROCESSING | Processing workflow task: 0 | Input task: None | Module: octo | Description: step1_octo
INFO | PROCESSING | Running task 0 for outer split 0

/Users/M228393/github/Octopus_public/.venv/lib/python3.12/site-packages/ray/_private/worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(

INFO | CREATING_DATASPLITS | 228 rows, 228 groups (column: datasplit_group), StratifiedGroupKFold, 3 splits, seed 0
INFO | CREATING_DATASPLITS | OUTER 0 SEQ TBD 0 created: Train - 152 rows, 152 groups | Dev - 76 rows, 76 groups
INFO | CREATING_DATASPLITS | OUTER 0 SEQ TBD 1 created: Train - 152 rows, 152 groups | Dev - 76 rows, 76 groups
INFO | CREATING_DATASPLITS | OUTER 0 SEQ TBD 2 created: Train - 152 rows, 152 groups | Dev - 76 rows, 76 groups
INFO | PREPARE_EXECUTION | Calculating MRMR feature sets...
INFO | PREPARE_EXECUTION | Running Optuna Optimization with a global HP set
INFO | PREPARE_EXECUTION | A new study created in memory with name: optuna_0_0

[I 2026-04-10 16:47:26,314] A new study created in memory with name: optuna_0_0

INFO | PREPARE_EXECUTION | Inner sequential training completed for bag_id 0_0_0 and training id 0_0_0
INFO | PREPARE_EXECUTION | Inner sequential training completed for bag_id 0_0_0 and training id 0_0_1
INFO | PREPARE_EXECUTION | Inner sequential training completed for bag_id 0_0_0 and training id 0_0_2
INFO | PREPARE_EXECUTION | Bag 0_0_0 training summary: 3/3 successful, 0 failed
INFO | SCORES | Trial scores for metric: AUCROC
INFO | SCORES | Scores: train_avg: 0.983 | dev_avg: 0.980 | test_avg: 0.987 | train_ensemble: 0.985 | dev_ensemble: 0.977 | test_ensemble: 0.988
INFO | SCORES | train_lst: [0.9750445632798573, 0.979483282674772, 0.9943406904357668]
INFO | SCORES | dev_lst: [0.9836647727272727, 0.9962207105064249, 0.9600000000000001]
INFO | SCORES | test_lst: [0.983512841756421, 0.9899751449875724, 0.9869925434962719]
INFO | SCORES | Otarget: 0.9769642122583299
INFO | SCORES | Number of features used: 0
INFO | SCORES | Trial 0 finished with value: 0.9769642122583299 and parameters: {'n_outliers': 2, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 24, 'min_samples_split_ExtraTreesClassifier': 61, 'min_samples_leaf_ExtraTreesClassifier': 28, 'max_features_ExtraTreesClassifier': 0.48128931940501424, 'n_estimators_ExtraTreesClassifier': 359, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 0 with value: 0.9769642122583299.

[I 2026-04-10 16:47:27,095] Trial 0 finished with value: 0.9769642122583299 and parameters: {'n_outliers': 2, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 24, 'min_samples_split_ExtraTreesClassifier': 61, 'min_samples_leaf_ExtraTreesClassifier': 28, 'max_features_ExtraTreesClassifier': 0.48128931940501424, 'n_estimators_ExtraTreesClassifier': 359, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 0 with value: 0.9769642122583299.

INFO | OPTUNA | Trial 0 finished with value: 0.9769642122583299 and parameters: {'n_outliers': 2, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 24, 'min_samples_split_ExtraTreesClassifier': 61, 'min_samples_leaf_ExtraTreesClassifier': 28, 'max_features_ExtraTreesClassifier': 0.48128931940501424, 'n_estimators_ExtraTreesClassifier': 359, 'class_weight_ExtraTreesClassifier': 'balanced'}
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_1 and training id 0_0_0
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_1 and training id 0_0_1
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_1 and training id 0_0_2
INFO | OPTUNA | Bag 0_0_1 training summary: 3/3 successful, 0 failed
INFO | SCORES | Trial scores for metric: AUCROC
INFO | SCORES | Scores: train_avg: 0.984 | dev_avg: 0.981 | test_avg: 0.987 | train_ensemble: 0.986 | dev_ensemble: 0.976 | test_ensemble: 0.988
INFO | SCORES | train_lst: [0.9767676767676767, 0.9787234042553191, 0.9953917050691244]
INFO | SCORES | dev_lst: [0.9850852272727273, 0.9962207105064249, 0.9607692307692308]
INFO | SCORES | test_lst: [0.9873239436619718, 0.9876553438276718, 0.9851698425849214]
INFO | SCORES | Otarget: 0.9763060468942822
INFO | SCORES | Number of features used: 0
INFO | SCORES | Trial 1 finished with value: 0.9763060468942822 and parameters: {'n_outliers': 3, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 13, 'min_samples_split_ExtraTreesClassifier': 80, 'min_samples_leaf_ExtraTreesClassifier': 27, 'max_features_ExtraTreesClassifier': 0.6112401049845391, 'n_estimators_ExtraTreesClassifier': 471, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 0 with value: 0.9769642122583299.

[I 2026-04-10 16:47:27,981] Trial 1 finished with value: 0.9763060468942822 and parameters: {'n_outliers': 3, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 13, 'min_samples_split_ExtraTreesClassifier': 80, 'min_samples_leaf_ExtraTreesClassifier': 27, 'max_features_ExtraTreesClassifier': 0.6112401049845391, 'n_estimators_ExtraTreesClassifier': 471, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 0 with value: 0.9769642122583299.

INFO | OPTUNA | Trial 1 finished with value: 0.9763060468942822 and parameters: {'n_outliers': 3, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 13, 'min_samples_split_ExtraTreesClassifier': 80, 'min_samples_leaf_ExtraTreesClassifier': 27, 'max_features_ExtraTreesClassifier': 0.6112401049845391, 'n_estimators_ExtraTreesClassifier': 471, 'class_weight_ExtraTreesClassifier': 'balanced'}
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_2 and training id 0_0_0
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_2 and training id 0_0_1
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_2 and training id 0_0_2
INFO | OPTUNA | Bag 0_0_2 training summary: 3/3 successful, 0 failed
INFO | SCORES | Trial scores for metric: AUCROC
INFO | SCORES | Scores: train_avg: 0.971 | dev_avg: 0.973 | test_avg: 0.980 | train_ensemble: 0.975 | dev_ensemble: 0.966 | test_ensemble: 0.980
INFO | SCORES | train_lst: [0.9584524490184868, 0.9671680117388115, 0.9887005649717514]
INFO | SCORES | dev_lst: [0.9808238636363636, 0.9901738473167045, 0.9492307692307693]
INFO | SCORES | test_lst: [0.9770505385252692, 0.9825186412593206, 0.9797845898922949]
INFO | SCORES | Otarget: 0.9658576717400247
INFO | SCORES | Number of features used: 0
INFO | SCORES | Trial 2 finished with value: 0.9658576717400247 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 27, 'min_samples_split_ExtraTreesClassifier': 79, 'min_samples_leaf_ExtraTreesClassifier': 44, 'max_features_ExtraTreesClassifier': 0.9807565080094877, 'n_estimators_ExtraTreesClassifier': 420, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 0 with value: 0.9769642122583299.

[I 2026-04-10 16:47:28,655] Trial 2 finished with value: 0.9658576717400247 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 27, 'min_samples_split_ExtraTreesClassifier': 79, 'min_samples_leaf_ExtraTreesClassifier': 44, 'max_features_ExtraTreesClassifier': 0.9807565080094877, 'n_estimators_ExtraTreesClassifier': 420, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 0 with value: 0.9769642122583299.

INFO | OPTUNA | Trial 2 finished with value: 0.9658576717400247 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 27, 'min_samples_split_ExtraTreesClassifier': 79, 'min_samples_leaf_ExtraTreesClassifier': 44, 'max_features_ExtraTreesClassifier': 0.9807565080094877, 'n_estimators_ExtraTreesClassifier': 420, 'class_weight_ExtraTreesClassifier': 'balanced'}
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_3 and training id 0_0_0
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_3 and training id 0_0_1
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_3 and training id 0_0_2
INFO | OPTUNA | Bag 0_0_3 training summary: 3/3 successful, 0 failed
INFO | SCORES | Trial scores for metric: AUCROC
INFO | SCORES | Scores: train_avg: 0.964 | dev_avg: 0.965 | test_avg: 0.975 | train_ensemble: 0.968 | dev_ensemble: 0.960 | test_ensemble: 0.977
INFO | SCORES | train_lst: [0.9544501619973319, 0.9528613352898019, 0.9837798432659013]
INFO | SCORES | dev_lst: [0.9779829545454546, 0.9833711262282692, 0.9338461538461538]
INFO | SCORES | test_lst: [0.9709196354598177, 0.9789560894780447, 0.9761391880695941]
INFO | SCORES | Otarget: 0.9598519127930893
INFO | SCORES | Number of features used: 0
INFO | SCORES | Trial 3 finished with value: 0.9598519127930893 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 21, 'min_samples_split_ExtraTreesClassifier': 16, 'min_samples_leaf_ExtraTreesClassifier': 48, 'max_features_ExtraTreesClassifier': 0.5696634895750645, 'n_estimators_ExtraTreesClassifier': 266, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 0 with value: 0.9769642122583299.

[I 2026-04-10 16:47:29,078] Trial 3 finished with value: 0.9598519127930893 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 21, 'min_samples_split_ExtraTreesClassifier': 16, 'min_samples_leaf_ExtraTreesClassifier': 48, 'max_features_ExtraTreesClassifier': 0.5696634895750645, 'n_estimators_ExtraTreesClassifier': 266, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 0 with value: 0.9769642122583299.

INFO | OPTUNA | Trial 3 finished with value: 0.9598519127930893 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 21, 'min_samples_split_ExtraTreesClassifier': 16, 'min_samples_leaf_ExtraTreesClassifier': 48, 'max_features_ExtraTreesClassifier': 0.5696634895750645, 'n_estimators_ExtraTreesClassifier': 266, 'class_weight_ExtraTreesClassifier': 'balanced'}
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_4 and training id 0_0_0
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_4 and training id 0_0_1
INFO | OPTUNA | Inner sequential training completed for bag_id 0_0_4 and training id 0_0_2
INFO | OPTUNA | Bag 0_0_4 training summary: 3/3 successful, 0 failed
INFO | SCORES | Trial scores for metric: AUCROC
INFO | SCORES | Scores: train_avg: 0.984 | dev_avg: 0.979 | test_avg: 0.987 | train_ensemble: 0.986 | dev_ensemble: 0.978 | test_ensemble: 0.988
INFO | SCORES | train_lst: [0.9757187257187256, 0.9807764091078761, 0.9955506117908787]
INFO | SCORES | dev_lst: [0.9815340909090908, 0.9962207105064249, 0.96]
INFO | SCORES | test_lst: [0.983761391880696, 0.987738193869097, 0.9887323943661972]
INFO | SCORES | Otarget: 0.9781982723159193
INFO | SCORES | Number of features used: 0
INFO | SCORES | Trial 4 finished with value: 0.9781982723159193 and parameters: {'n_outliers': 1, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 19, 'min_samples_split_ExtraTreesClassifier': 3, 'min_samples_leaf_ExtraTreesClassifier': 31, 'max_features_ExtraTreesClassifier': 0.6508861504501793, 'n_estimators_ExtraTreesClassifier': 347, 'class_weight_ExtraTreesClassifier': None}. Best is trial 4 with value: 0.9781982723159193.

[I 2026-04-10 16:47:29,868] Trial 4 finished with value: 0.9781982723159193 and parameters: {'n_outliers': 1, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 19, 'min_samples_split_ExtraTreesClassifier': 3, 'min_samples_leaf_ExtraTreesClassifier': 31, 'max_features_ExtraTreesClassifier': 0.6508861504501793, 'n_estimators_ExtraTreesClassifier': 347, 'class_weight_ExtraTreesClassifier': None}. Best is trial 4 with value: 0.9781982723159193.

INFO | OPTUNA | Trial 4 finished with value: 0.9781982723159193 and parameters: {'n_outliers': 1, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 19, 'min_samples_split_ExtraTreesClassifier': 3, 'min_samples_leaf_ExtraTreesClassifier': 31, 'max_features_ExtraTreesClassifier': 0.6508861504501793, 'n_estimators_ExtraTreesClassifier': 347, 'class_weight_ExtraTreesClassifier': None}
INFO | SCORES | Optimization results:
INFO | SCORES | Best trial number 4
INFO | SCORES | Best target value 0.9781982723159193
INFO | SCORES | Best parameters {'outl_reduction': 1, 'n_input_features': 30, 'ml_model_type': <ModelName.ExtraTreesClassifier: 'ExtraTreesClassifier'>, 'ml_model_params': {'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 31, 'max_features': 0.6508861504501793, 'n_estimators': 347, 'class_weight': None, 'criterion': 'entropy', 'bootstrap': True, 'n_jobs': 1, 'random_state': 0}, 'positive_class': 1}
INFO | SCORES | Performance Info: {'train_avg': 0.9840152488724935, 'train_lst': [0.9757187257187256, 0.9807764091078761, 0.9955506117908787], 'dev_avg': 0.9792516004718386, 'dev_lst': [0.9815340909090908, 0.9962207105064249, 0.96], 'test_avg': 0.9867439933719967, 'test_lst': [0.983761391880696, 0.987738193869097, 0.9887323943661972], 'train_ensemble': 0.9858474858474859, 'dev_ensemble': 0.9781982723159193, 'test_ensemble': 0.987986743993372}
INFO | SCORES | Create best bag.....
INFO | SCORES | Inner sequential training completed for bag_id 0_0_best and training id 0_0_0
INFO | SCORES | Inner sequential training completed for bag_id 0_0_best and training id 0_0_1
INFO | SCORES | Inner sequential training completed for bag_id 0_0_best and training id 0_0_2
INFO | SCORES | Bag 0_0_best training summary: 3/3 successful, 0 failed
INFO | SCORES | Best bag performance {'train_avg': 0.9840152488724935, 'train_lst': [0.9757187257187256, 0.9807764091078761, 0.9955506117908787], 'dev_avg': 0.9792516004718386, 'dev_lst': [0.9815340909090908, 0.9962207105064249, 0.96], 'test_avg': 0.9867439933719967, 'test_lst': [0.983761391880696, 0.987738193869097, 0.9887323943661972], 'train_ensemble': 0.9858474858474859, 'dev_ensemble': 0.9781982723159193, 'test_ensemble': 0.987986743993372}
INFO | RESULTS | Training: 0_0 AUCROC (best bag - ensembled): Dev 0.978, Test 0.988
INFO | RESULTS | Feature importance (internal) calculation completed for bag_id 0_0_best and training id 0_0_0
INFO | RESULTS | Feature importance (internal) calculation completed for bag_id 0_0_best and training id 0_0_1
INFO | RESULTS | Feature importance (internal) calculation completed for bag_id 0_0_best and training id 0_0_2
INFO | RESULTS | Bag 0_0_best feature importance (internal) summary: 3/3 successful, 0 failed
INFO | TRAINING | Calculating permutation feature importances (dev). This may take a while...
INFO | TRAINING | Feature importance (permutation) calculation completed for bag_id 0_0_best and training id 0_0_0
INFO | TRAINING | Calculating permutation feature importances (dev). This may take a while...
INFO | TRAINING | Feature importance (permutation) calculation completed for bag_id 0_0_best and training id 0_0_1
INFO | TRAINING | Calculating permutation feature importances (dev). This may take a while...
INFO | TRAINING | Feature importance (permutation) calculation completed for bag_id 0_0_best and training id 0_0_2
INFO | TRAINING | Bag 0_0_best feature importance (permutation) summary: 3/3 successful, 0 failed
INFO | RESULTS | Number of selected features: 28
INFO | RESULTS | Number of single features: 28
INFO | RESULTS | Number of features from groups: 0
INFO | RESULTS | ---
INFO | RESULTS | Number of original features: 30
INFO | RESULTS | Number of selected features: 28
INFO | RESULTS | Running outer split: 1
INFO | RESULTS | Processing workflow task: 0 | Input task: None | Module: octo | Description: step1_octo
INFO | RESULTS | Running task 0 for outer split 1
INFO | CREATING_DATASPLITS | 227 rows, 227 groups (column: datasplit_group), StratifiedGroupKFold, 3 splits, seed 0
INFO | CREATING_DATASPLITS | OUTER 1 SEQ TBD 0 created: Train - 151 rows, 151 groups | Dev - 76 rows, 76 groups
INFO | CREATING_DATASPLITS | OUTER 1 SEQ TBD 1 created: Train - 151 rows, 151 groups | Dev - 76 rows, 76 groups
INFO | CREATING_DATASPLITS | OUTER 1 SEQ TBD 2 created: Train - 152 rows, 152 groups | Dev - 75 rows, 75 groups
INFO | PREPARE_EXECUTION | Calculating MRMR feature sets...
INFO | PREPARE_EXECUTION | Running Optuna Optimization with a global HP set
INFO | PREPARE_EXECUTION | A new study created in memory with name: optuna_1_0

/Users/M228393/github/Octopus_public/octopus/utils.py:93: UserWarning: The DataFrame has column names of mixed type. They will be converted to strings and not roundtrip correctly.
  table = pa.Table.from_pandas(df, preserve_index=index)
[I 2026-04-10 16:47:37,288] A new study created in memory with name: optuna_1_0

INFO | PREPARE_EXECUTION | Inner sequential training completed for bag_id 1_0_0 and training id 1_0_0
INFO | PREPARE_EXECUTION | Inner sequential training completed for bag_id 1_0_0 and training id 1_0_1
INFO | PREPARE_EXECUTION | Inner sequential training completed for bag_id 1_0_0 and training id 1_0_2
INFO | PREPARE_EXECUTION | Bag 1_0_0 training summary: 3/3 successful, 0 failed
INFO | SCORES | Trial scores for metric: AUCROC
INFO | SCORES | Scores: train_avg: 0.989 | dev_avg: 0.987 | test_avg: 0.979 | train_ensemble: 0.989 | dev_ensemble: 0.987 | test_ensemble: 0.980
INFO | SCORES | train_lst: [0.9907721280602636, 0.9862811312790207, 0.9885798489592927]
INFO | SCORES | dev_lst: [0.9823717948717948, 0.9916897506925209, 0.9866220735785953]
INFO | SCORES | test_lst: [0.9802550390785685, 0.9781160016454133, 0.9791032496914849]
INFO | SCORES | Otarget: 0.9870753935376968
INFO | SCORES | Number of features used: 0
INFO | SCORES | Trial 0 finished with value: 0.9870753935376968 and parameters: {'n_outliers': 2, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 24, 'min_samples_split_ExtraTreesClassifier': 61, 'min_samples_leaf_ExtraTreesClassifier': 28, 'max_features_ExtraTreesClassifier': 0.48128931940501424, 'n_estimators_ExtraTreesClassifier': 359, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 0 with value: 0.9870753935376968.

[I 2026-04-10 16:47:38,002] Trial 0 finished with value: 0.9870753935376968 and parameters: {'n_outliers': 2, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 24, 'min_samples_split_ExtraTreesClassifier': 61, 'min_samples_leaf_ExtraTreesClassifier': 28, 'max_features_ExtraTreesClassifier': 0.48128931940501424, 'n_estimators_ExtraTreesClassifier': 359, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 0 with value: 0.9870753935376968.

INFO | OPTUNA | Trial 0 finished with value: 0.9870753935376968 and parameters: {'n_outliers': 2, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 24, 'min_samples_split_ExtraTreesClassifier': 61, 'min_samples_leaf_ExtraTreesClassifier': 28, 'max_features_ExtraTreesClassifier': 0.48128931940501424, 'n_estimators_ExtraTreesClassifier': 359, 'class_weight_ExtraTreesClassifier': 'balanced'}
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_1 and training id 1_0_0
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_1 and training id 1_0_1
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_1 and training id 1_0_2
INFO | OPTUNA | Bag 1_0_1 training summary: 3/3 successful, 0 failed
INFO | SCORES | Trial scores for metric: AUCROC
INFO | SCORES | Scores: train_avg: 0.990 | dev_avg: 0.989 | test_avg: 0.980 | train_ensemble: 0.989 | dev_ensemble: 0.989 | test_ensemble: 0.980
INFO | SCORES | train_lst: [0.9913793103448276, 0.9883495145631067, 0.9893258426966292]
INFO | SCORES | dev_lst: [0.985576923076923, 0.9916897506925207, 0.9891304347826088]
INFO | SCORES | test_lst: [0.9810777457836282, 0.9786096256684492, 0.9797614150555327]
INFO | SCORES | Otarget: 0.9885666942833472
INFO | SCORES | Number of features used: 0
INFO | SCORES | Trial 1 finished with value: 0.9885666942833472 and parameters: {'n_outliers': 3, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 13, 'min_samples_split_ExtraTreesClassifier': 80, 'min_samples_leaf_ExtraTreesClassifier': 27, 'max_features_ExtraTreesClassifier': 0.6112401049845391, 'n_estimators_ExtraTreesClassifier': 471, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 1 with value: 0.9885666942833472.

[I 2026-04-10 16:47:38,874] Trial 1 finished with value: 0.9885666942833472 and parameters: {'n_outliers': 3, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 13, 'min_samples_split_ExtraTreesClassifier': 80, 'min_samples_leaf_ExtraTreesClassifier': 27, 'max_features_ExtraTreesClassifier': 0.6112401049845391, 'n_estimators_ExtraTreesClassifier': 471, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 1 with value: 0.9885666942833472.

INFO | OPTUNA | Trial 1 finished with value: 0.9885666942833472 and parameters: {'n_outliers': 3, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 13, 'min_samples_split_ExtraTreesClassifier': 80, 'min_samples_leaf_ExtraTreesClassifier': 27, 'max_features_ExtraTreesClassifier': 0.6112401049845391, 'n_estimators_ExtraTreesClassifier': 471, 'class_weight_ExtraTreesClassifier': 'balanced'}
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_2 and training id 1_0_0
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_2 and training id 1_0_1
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_2 and training id 1_0_2
INFO | OPTUNA | Bag 1_0_2 training summary: 3/3 successful, 0 failed
INFO | SCORES | Trial scores for metric: AUCROC
INFO | SCORES | Scores: train_avg: 0.987 | dev_avg: 0.983 | test_avg: 0.969 | train_ensemble: 0.989 | dev_ensemble: 0.976 | test_ensemble: 0.972
INFO | SCORES | train_lst: [0.9879781420765027, 0.9844517184942716, 0.9887096774193548]
INFO | SCORES | dev_lst: [0.983173076923077, 0.9833795013850416, 0.9832775919732442]
INFO | SCORES | test_lst: [0.9680789798436858, 0.9657754010695186, 0.9734265734265733]
INFO | SCORES | Otarget: 0.9758906379453189
INFO | SCORES | Number of features used: 0
INFO | SCORES | Trial 2 finished with value: 0.9758906379453189 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 27, 'min_samples_split_ExtraTreesClassifier': 79, 'min_samples_leaf_ExtraTreesClassifier': 44, 'max_features_ExtraTreesClassifier': 0.9807565080094877, 'n_estimators_ExtraTreesClassifier': 420, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 1 with value: 0.9885666942833472.

[I 2026-04-10 16:47:39,507] Trial 2 finished with value: 0.9758906379453189 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 27, 'min_samples_split_ExtraTreesClassifier': 79, 'min_samples_leaf_ExtraTreesClassifier': 44, 'max_features_ExtraTreesClassifier': 0.9807565080094877, 'n_estimators_ExtraTreesClassifier': 420, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 1 with value: 0.9885666942833472.

INFO | OPTUNA | Trial 2 finished with value: 0.9758906379453189 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 27, 'min_samples_split_ExtraTreesClassifier': 79, 'min_samples_leaf_ExtraTreesClassifier': 44, 'max_features_ExtraTreesClassifier': 0.9807565080094877, 'n_estimators_ExtraTreesClassifier': 420, 'class_weight_ExtraTreesClassifier': 'balanced'}
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_3 and training id 1_0_0
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_3 and training id 1_0_1
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_3 and training id 1_0_2
INFO | OPTUNA | Bag 1_0_3 training summary: 3/3 successful, 0 failed
INFO | SCORES | Trial scores for metric: AUCROC
INFO | SCORES | Scores: train_avg: 0.984 | dev_avg: 0.978 | test_avg: 0.965 | train_ensemble: 0.985 | dev_ensemble: 0.955 | test_ensemble: 0.969
INFO | SCORES | train_lst: [0.9806921675774134, 0.9914075286415711, 0.9793906810035842]
INFO | SCORES | dev_lst: [0.9575320512820513, 0.9979224376731302, 0.9774247491638796]
INFO | SCORES | test_lst: [0.9515837104072399, 0.9750719868366927, 0.967420814479638]
INFO | SCORES | Otarget: 0.9549295774647888
INFO | SCORES | Number of features used: 0
INFO | SCORES | Trial 3 finished with value: 0.9549295774647888 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 21, 'min_samples_split_ExtraTreesClassifier': 16, 'min_samples_leaf_ExtraTreesClassifier': 48, 'max_features_ExtraTreesClassifier': 0.5696634895750645, 'n_estimators_ExtraTreesClassifier': 266, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 1 with value: 0.9885666942833472.

[I 2026-04-10 16:47:39,941] Trial 3 finished with value: 0.9549295774647888 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 21, 'min_samples_split_ExtraTreesClassifier': 16, 'min_samples_leaf_ExtraTreesClassifier': 48, 'max_features_ExtraTreesClassifier': 0.5696634895750645, 'n_estimators_ExtraTreesClassifier': 266, 'class_weight_ExtraTreesClassifier': 'balanced'}. Best is trial 1 with value: 0.9885666942833472.

INFO | OPTUNA | Trial 3 finished with value: 0.9549295774647888 and parameters: {'n_outliers': 0, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 21, 'min_samples_split_ExtraTreesClassifier': 16, 'min_samples_leaf_ExtraTreesClassifier': 48, 'max_features_ExtraTreesClassifier': 0.5696634895750645, 'n_estimators_ExtraTreesClassifier': 266, 'class_weight_ExtraTreesClassifier': 'balanced'}
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_4 and training id 1_0_0
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_4 and training id 1_0_1
INFO | OPTUNA | Inner sequential training completed for bag_id 1_0_4 and training id 1_0_2
INFO | OPTUNA | Bag 1_0_4 training summary: 3/3 successful, 0 failed
INFO | SCORES | Trial scores for metric: AUCROC
INFO | SCORES | Scores: train_avg: 0.989 | dev_avg: 0.987 | test_avg: 0.978 | train_ensemble: 0.990 | dev_ensemble: 0.981 | test_ensemble: 0.979
INFO | SCORES | train_lst: [0.990925925925926, 0.9869861598843214, 0.9885245901639345]
INFO | SCORES | dev_lst: [0.9823717948717949, 0.9916897506925209, 0.9857859531772576]
INFO | SCORES | test_lst: [0.9788564376799671, 0.9770464829288359, 0.979020979020979]
INFO | SCORES | Otarget: 0.9806959403479703
INFO | SCORES | Number of features used: 0
INFO | SCORES | Trial 4 finished with value: 0.9806959403479703 and parameters: {'n_outliers': 1, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 19, 'min_samples_split_ExtraTreesClassifier': 3, 'min_samples_leaf_ExtraTreesClassifier': 31, 'max_features_ExtraTreesClassifier': 0.6508861504501793, 'n_estimators_ExtraTreesClassifier': 347, 'class_weight_ExtraTreesClassifier': None}. Best is trial 1 with value: 0.9885666942833472.

[I 2026-04-10 16:47:40,625] Trial 4 finished with value: 0.9806959403479703 and parameters: {'n_outliers': 1, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 19, 'min_samples_split_ExtraTreesClassifier': 3, 'min_samples_leaf_ExtraTreesClassifier': 31, 'max_features_ExtraTreesClassifier': 0.6508861504501793, 'n_estimators_ExtraTreesClassifier': 347, 'class_weight_ExtraTreesClassifier': None}. Best is trial 1 with value: 0.9885666942833472.

INFO | OPTUNA | Trial 4 finished with value: 0.9806959403479703 and parameters: {'n_outliers': 1, 'n_mrmr_features': 30, 'max_depth_ExtraTreesClassifier': 19, 'min_samples_split_ExtraTreesClassifier': 3, 'min_samples_leaf_ExtraTreesClassifier': 31, 'max_features_ExtraTreesClassifier': 0.6508861504501793, 'n_estimators_ExtraTreesClassifier': 347, 'class_weight_ExtraTreesClassifier': None}
INFO | SCORES | Optimization results:
INFO | SCORES | Best trial number 1
INFO | SCORES | Best target value 0.9885666942833472
INFO | SCORES | Best parameters {'outl_reduction': 3, 'n_input_features': 30, 'ml_model_type': <ModelName.ExtraTreesClassifier: 'ExtraTreesClassifier'>, 'ml_model_params': {'max_depth': 13, 'min_samples_split': 80, 'min_samples_leaf': 27, 'max_features': 0.6112401049845391, 'n_estimators': 471, 'class_weight': 'balanced', 'criterion': 'entropy', 'bootstrap': True, 'n_jobs': 1, 'random_state': 0}, 'positive_class': 1}
INFO | SCORES | Performance Info: {'train_avg': 0.9896848892015212, 'train_lst': [0.9913793103448276, 0.9883495145631067, 0.9893258426966292], 'dev_avg': 0.9887990361840175, 'dev_lst': [0.985576923076923, 0.9916897506925207, 0.9891304347826088], 'test_avg': 0.9798162621692034, 'test_lst': [0.9810777457836282, 0.9786096256684492, 0.9797614150555327], 'train_ensemble': 0.9894044262155004, 'dev_ensemble': 0.9885666942833472, 'test_ensemble': 0.9802550390785685}
INFO | SCORES | Create best bag.....
INFO | SCORES | Inner sequential training completed for bag_id 1_0_best and training id 1_0_0
INFO | SCORES | Inner sequential training completed for bag_id 1_0_best and training id 1_0_1
INFO | SCORES | Inner sequential training completed for bag_id 1_0_best and training id 1_0_2
INFO | SCORES | Bag 1_0_best training summary: 3/3 successful, 0 failed
INFO | SCORES | Best bag performance {'train_avg': 0.9896848892015212, 'train_lst': [0.9913793103448276, 0.9883495145631067, 0.9893258426966292], 'dev_avg': 0.9887990361840175, 'dev_lst': [0.985576923076923, 0.9916897506925207, 0.9891304347826088], 'test_avg': 0.9798162621692034, 'test_lst': [0.9810777457836282, 0.9786096256684492, 0.9797614150555327], 'train_ensemble': 0.9894044262155004, 'dev_ensemble': 0.9885666942833472, 'test_ensemble': 0.9802550390785685}
INFO | RESULTS | Training: 1_0 AUCROC (best bag - ensembled): Dev 0.989, Test 0.980
INFO | RESULTS | Feature importance (internal) calculation completed for bag_id 1_0_best and training id 1_0_0
INFO | RESULTS | Feature importance (internal) calculation completed for bag_id 1_0_best and training id 1_0_1
INFO | RESULTS | Feature importance (internal) calculation completed for bag_id 1_0_best and training id 1_0_2
INFO | RESULTS | Bag 1_0_best feature importance (internal) summary: 3/3 successful, 0 failed
INFO | TRAINING | Calculating permutation feature importances (dev). This may take a while...
INFO | TRAINING | Feature importance (permutation) calculation completed for bag_id 1_0_best and training id 1_0_0
INFO | TRAINING | Calculating permutation feature importances (dev). This may take a while...
INFO | TRAINING | Feature importance (permutation) calculation completed for bag_id 1_0_best and training id 1_0_1
INFO | TRAINING | Calculating permutation feature importances (dev). This may take a while...
INFO | TRAINING | Feature importance (permutation) calculation completed for bag_id 1_0_best and training id 1_0_2
INFO | TRAINING | Bag 1_0_best feature importance (permutation) summary: 3/3 successful, 0 failed
INFO | RESULTS | Number of selected features: 20
INFO | RESULTS | Number of single features: 20
INFO | RESULTS | Number of features from groups: 0
INFO | RESULTS | ---
INFO | RESULTS | Number of original features: 30
INFO | RESULTS | Number of selected features: 20

/Users/M228393/github/Octopus_public/octopus/utils.py:93: UserWarning: The DataFrame has column names of mixed type. They will be converted to strings and not roundtrip correctly.
  table = pa.Table.from_pandas(df, preserve_index=index)

INFO | RESULTS | Study completed. Results saved to: studies/predict_example-20260410_144723
Study saved to: studies/predict_example-20260410_144723

## 2. Load the Study

In [6]:
from octopus.predict.study_io import load_study_info

study_info = load_study_info(study.output_path)

print(f"ML type: {study_info.config['ml_type']}")
print(f"Target metric: {study_info.config['target_metric']}")
print(f"Outer splits: {len(study_info.outer_split_dirs)}")
print(f"Features: {len(study_info.config['feature_cols'])}")

ML type: binary
Target metric: AUCROC
Outer splits: 2
Features: 30

## 3. Create an OctoPredictor

In [7]:
from octopus.predict import OctoPredictor

tp = OctoPredictor(study=study_info, task_id=0)
print(f"Loaded models for {len(tp._models)} outer splits")

Loaded models for 2 outer splits

## 4. Predict on New Data

Each outer-split model predicts independently, then results are averaged into an ensemble prediction. Use `per_split=True` to see individual split predictions.

In [9]:
# Ensemble-averaged predictions (row_id + prediction)
predictions = tp.predict(new_df, per_split=True)
predictions.head(10)

   row_id  prediction  split_0  split_1
0       0         0.0      0.0      0.0
1       1         1.0      1.0      1.0
2       2         0.0      0.0      0.0
3       3         0.5      1.0      0.0
4       4         0.0      0.0      0.0
5       5         1.0      1.0      1.0
6       6         1.0      1.0      1.0
7       7         0.0      0.0      0.0
8       8         0.0      0.0      0.0
9       9         0.0      0.0      0.0

In [10]:
# With per-split predictions as additional columns
predictions_detail = tp.predict(new_df, per_split=True)
predictions_detail.head(10)

   row_id  prediction  split_0  split_1
0       0         0.0      0.0      0.0
1       1         1.0      1.0      1.0
2       2         0.0      0.0      0.0
3       3         0.5      1.0      0.0
4       4         0.0      0.0      0.0
5       5         1.0      1.0      1.0
6       6         1.0      1.0      1.0
7       7         0.0      0.0      0.0
8       8         0.0      0.0      0.0
9       9         0.0      0.0      0.0

## 5. Predict Probabilities

For classification tasks, `predict_proba` returns class probabilities.

In [11]:
# Ensemble-averaged probabilities (row_id + one column per class)
proba = tp.predict_proba(new_df)
proba.head(10)

   row_id         0         1
0       0  0.769965  0.230035
1       1  0.111642  0.888358
2       2  0.661370  0.338630
3       3  0.486047  0.513953
4       4  0.758067  0.241933
5       5  0.237224  0.762776
6       6  0.165245  0.834755
7       7  0.767734  0.232266
8       8  0.754870  0.245130
9       9  0.776588  0.223412

In [12]:
# With per-split probabilities as additional columns
proba_detail = tp.predict_proba(new_df, per_split=True)
proba_detail.head(10)

   row_id         0         1  0_split_0  1_split_0  0_split_1  1_split_1
0       0  0.769965  0.230035   0.706793   0.293207   0.833136   0.166864
1       1  0.111642  0.888358   0.095758   0.904242   0.127526   0.872474
2       2  0.661370  0.338630   0.603109   0.396891   0.719632   0.280368
3       3  0.486047  0.513953   0.411730   0.588270   0.560363   0.439637
4       4  0.758067  0.241933   0.690868   0.309132   0.825266   0.174734
5       5  0.237224  0.762776   0.177542   0.822458   0.296907   0.703093
6       6  0.165245  0.834755   0.161854   0.838146   0.168637   0.831363
7       7  0.767734  0.232266   0.703820   0.296180   0.831648   0.168352
8       8  0.754870  0.245130   0.688977   0.311023   0.820762   0.179238
9       9  0.776588  0.223412   0.714466   0.285534   0.838710   0.161290

## 6. Evaluate Performance

Score each outer-split model on the held-out new data.

In [13]:
perf = tp.performance(new_df, metrics=["AUCROC", "ACCBAL"])
perf

   outer_split  metric     score
0            0  AUCROC  0.989749
1            0  ACCBAL  0.919643
2            1  AUCROC  0.987765
3            1  ACCBAL  0.913690

## 7. Save and Load for Deployment

Save the predictor to a standalone directory (models + metadata only, no data). Load it back and verify predictions match.

In [14]:
# Save to a temporary directory
save_dir = tempfile.mkdtemp(prefix="octopus_predictor_")
tp.save(save_dir)
print(f"Saved predictor to: {save_dir}")
print(f"Contents: {os.listdir(save_dir)}")

Saved predictor to: /var/folders/lr/x666zkrd2mn_6l3v8kg0kv_h0000gn/T/octopus_predictor_u2k5mpzn
Contents: ['selected_features', 'version.json', 'models', 'study_config.json', 'predictor_state.json']

In [15]:
# Load the saved predictor (no study directory needed)
tp_loaded = OctoPredictor.load(save_dir)

# Verify predictions match
predictions_loaded = tp_loaded.predict(new_df)
pd.testing.assert_frame_equal(predictions, predictions_loaded)
print("Predictions match after save/load.")

NameError: name 'pd' is not defined